# Main site settings
title: Guava
subtitle: Google core libraries for Java
description: Google core libraries for Java
baseurl: /guava
url: http://google.github.io
permalink: /news/:year/:month/:day/:title/

exclude:
- "Gemfile*"
- "README.md"
- "*.sh"

# Set by default by GitHub pages (can't be changed)
safe: true
lsi: false
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
# source: <top level directory>

# Set by default by GitHub pages (can be changed)
# github: <repository metadata> (https://help.github.com/articles/repository-metadata-on-github-pages/)

# Collections
#collections:
# releases collection disabled until there's non-Javadoc/JDiff content that needs to go there
# Files under the releases/ directory (where the Javadoc/JDiff is kept) are included directly.
# When there are .md files that need rendering, they should go under _releases and this collection
# should be re-enabled.
# releases:
#   output: true
#   permalink: /:collection/:path/

# Release data
# Do not change! updaterelease.sh automatically updates these fields
latest_release: 18.0
latest_snapshot: 20.0-SNAPSHOT

# Miscellaneous data
email: guava-discuss@googlegroups.com
twitter_username: GoogleGuava
github_username:  google/guava
