# Main site settings
title: Guava
subtitle: Google core libraries for Java
description: Google core libraries for Java
baseurl: /
url: https://guava.dev

themeColor: red

exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _site
  - node_modules
  - vendor
  - "*.sh"

plugins:
  - jekyll-redirect-from

# Release data
# Do not change! updaterelease.sh automatically updates these fields
latest_release: 33.2.0

# Miscellaneous data
email: guava-discuss@googlegroups.com
twitter_username: GoogleGuava
github_username:  google/guava
